### ISSUE TITLE
Gradle sync error

### ISSUE THREAD

**Issue by jihoon1319** [jihoon1319/GloriousFamily#9]
![2015-07-26 2 53 48](https://cloud.githubusercontent.com/assets/6879002/8890609/9ff64b9a-3341-11e5-90c9-21f1fd24299a.png)

This Gradle sync error occurs from the first time I started my project. I selected a JDK(1.6.0) from the file system, but this error doesn't disappear. The weird thing is, my project builds and runs well. What's this error message?

**Comment by minhoryang** [comment]
```bash
brew cask install java7
```

**Comment by jihoon1319** [comment]
Plus: setting path "/System/Library/Frameworks/JavaVM.framework/Home" is working for me.
